### ISSUE TITLE
YaBCS: Generated Partset XML in CostCreate error

### ISSUE THREAD

**Issue by Sportiax** [KyonkoYuuki/YaBCSOrganizer#1]
![Annotation 2020-05-25 150840](https://user-images.githubusercontent.com/65922219/82841165-ad6d6000-9e9a-11ea-95a4-da9640803f7c.png)
![Annotation 2020-05-25 150857](https://user-images.githubusercontent.com/65922219/82841178-b3fbd780-9e9a-11ea-95b8-a8a2c9af2467.png)
Hoping the above links open the pictures correctly, if not, dialog boxes are explained below.
First dialog box shows "cannot read the parameter string_28"
The second dialog box shows "On HUM/SYM Partset 0: BCS compilation error"

**Comment by KyonkoYuuki** [comment]
Whoops, thats for the Physics part.  The FILES section should read STR_28.  Fixed for next version.
